export const FORM_CONSTANTS = {
  auth: {
    header: 'Авторизация',
    text: 'Авторизируйтесь, чтобы начать публиковать свои объявления',
    rememberMe: 'Запомнить меня',
    forgotPassword: 'Забыли пароль?',
    hint: 'Еще нет аккаунта?',
    hintLink: 'Создайте акканут',
  },
  reg: {
    header: 'Регистрация',
  },
  errors: {
    notEmpty: 'Это поле не может быть пустым',
    email: 'Введите корректный email',
    name: 'Введите корректное имя',
    login: 'Введите корректный логин',
    password: 'Введите корректный пароль',
  },
  regexp: {
    email: /^[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[A-Za-z]+$/,
  },
  labels: {
    email: 'Ваша электронная почта',
    name: 'Ваше имя',
    message: 'Ваше сообщение',
    location: 'Город',
    rooms: 'Комнаты',
    priceDay: 'Цена за сутки (BYN)',
    from: 'От',
    to: 'До',
  },
  placeholders: {
    email: 'Введите email',
    name: 'Введите имя',
    message: 'Сообщение',
    metro: 'Метро',
    district: 'Район',
    search: 'Поиск по статьям',
    login: 'Логин',
    password: 'Пароль',
  },
  filters: {
    options: 'Больше опций',
    map: 'На карте',
  },
  buttons: {
    send: 'Отправить',
    reset: 'Очистить',
    show: 'Показать',
    more: 'Подробнее',
    contacts: 'Контакты',
    login: 'Войти',
  },
};
