export enum ButtonStyleType {
  HIGHLIGHT = 'highlight',
  BASE = 'base',
  YELLOW = 'yellow',
  PURPLE = 'purple',
  BIG = 'big',
  SMALL = 'small',
  MINI = 'mini',
  BASE_V2 = 'baseV2',
  BASE_V3 = 'baseV3',
  BASE_V4 = 'baseV4',
  YELLOW_V2 = 'yellowV2',
  CIRCLE = 'circle',
  COMMON = 'common',
}
